name: Run basic scripts to check for syntactical correctness
on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-xml-linter-on-sanbox:
    name: XML linter for sandbox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
#      - run: apt-get install -y libxml2-utils
      - run: xmllint "Naust Sandbox.wsb"
